export const ADD_TO_EQUATION = 'ADD_TO_EQUATION';
export const CHANGE_ZERO = 'CHANGE_ZERO'
export const DEL_CHAR_FROM_EQUATION = 'DEL_CHAR_FROM_EQUATION ';
export const REMOVE_EQUATION = 'REMOVE_EQUATION';

export const SHOW_RESULT_OF_EQUATION = 'SHOW_RESULT_OF_EQUATION';